package io.github.lchareln.cex.matching.testkit;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** Runs the frozen M03 semantic suite without rebinding M03's historical source-identity gate. */
final class M04LegacyRegression {
  static final String EXPECTED_DIGEST =
      "sha256:1920d6b8a480998825c72636d446854d9e795e91b0ab29520f203b12186979ce";
  static final int EXPECTED_BYTES = 1_682_592;
  static final int EXPECTED_LINES = 16_641;
  static final int EXPECTED_COMMANDS = 16_384;

  Result run(Path root) {
    M03GeneratorProfile profile =
        M03GeneratorProfile.load(
            root.resolve(M03StartCheckRunner.GENERATOR_PATH),
            root.resolve(M03StartCheckRunner.GENERATOR_SCHEMA_PATH));
    M03HistoryGenerator generator = new M03HistoryGenerator();
    List<M03GeneratedHistory> histories = generator.generate(profile);
    M03CommandCanonicalizer canonicalizer = new M03CommandCanonicalizer();
    M03CommandCanonicalizer.CanonicalCommands generated =
        canonicalizer.canonicalize(profile, histories);
    M03CommandCanonicalizer.CanonicalCommands regenerated =
        canonicalizer.canonicalize(profile, generator.generate(profile));
    require(Arrays.equals(generated.bytes(), regenerated.bytes()), "M03 regenerated bytes changed");
    require(generated.digest().equals(regenerated.digest()), "M03 regenerated digest changed");
    require(EXPECTED_DIGEST.equals(generated.digest()), "M03G1 command digest changed");
    require(EXPECTED_BYTES == generated.bytes().length, "M03G1 command byte count changed");
    require(EXPECTED_LINES == countLines(generated.bytes()), "M03G1 command line count changed");
    require(EXPECTED_COMMANDS == generated.commandCount(), "M03 command count changed");

    M03PropertyJudge judge = new M03PropertyJudge();
    int comparisons = 0;
    int ledgerChecks = 0;
    int bookChecks = 0;
    for (M03GeneratedHistory history : histories) {
      M03PropertyJudge.Observation observation = judge.judge(history, M03ProductionCandidate::new);
      require(
          M03PropertyJudge.PASS.equals(observation.classification()),
          "M03 neutral GTC regression failed at history " + history.historyIndex());
      comparisons += observation.differentialComparisons();
      ledgerChecks += observation.ledgerChecks();
      bookChecks += observation.bookChecks();
    }
    require(comparisons == EXPECTED_COMMANDS, "M03 differential comparison count changed");
    require(ledgerChecks == EXPECTED_COMMANDS, "M03 ledger check count changed");
    require(bookChecks == EXPECTED_COMMANDS, "M03 book check count changed");

    List<MutantFact> mutantFacts = new ArrayList<>();
    for (RequiredMutant mutant : requiredMutants()) {
      FailureSource source = find(histories, mutant, judge);
      M03Shrinker.Result shrunk =
          new M03Shrinker()
              .shrink(
                  "m04-legacy-" + mutant.id(),
                  source.history().seedHex(),
                  source.history().commands(),
                  mutant.factory(),
                  mutant.fingerprint());
      require(shrunk.oneMinimal(), "M03 legacy counterexample is not one-minimal: " + mutant.id());
      require(
          mutant.fingerprint().matches(shrunk.observation()),
          "M03 legacy counterexample fingerprint changed: " + mutant.id());
      mutantFacts.add(
          new MutantFact(
              mutant.id(),
              mutant.fingerprint().value(),
              source.history().historyIndex(),
              source.history().laneId(),
              source.history().seedHex(),
              source.history().commands().size(),
              shrunk.commands().size(),
              shrunk.trials(),
              shrunk.oneMinimal()));
    }
    M03PropertyJudge.Observation throwing =
        judge.judge(histories.getFirst(), M03Mutants.throwingControl());
    require(
        M03PropertyJudge.SYSTEM_ERROR.equals(throwing.classification()),
        "M03 throwing control did not remain SYSTEM_ERROR");
    return new Result(
        histories.size(),
        generated.commandCount(),
        generated.bytes().length,
        countLines(generated.bytes()),
        generated.digest(),
        comparisons,
        ledgerChecks,
        bookChecks,
        mutantFacts,
        throwing.classification());
  }

  private static FailureSource find(
      List<M03GeneratedHistory> histories, RequiredMutant mutant, M03PropertyJudge judge) {
    for (M03GeneratedHistory history : histories) {
      M03PropertyJudge.Observation observation = judge.judge(history, mutant.factory());
      if (M03PropertyJudge.SYSTEM_ERROR.equals(observation.classification())) {
        throw new IllegalStateException("M03 legacy mutant raised SYSTEM_ERROR: " + mutant.id());
      }
      if (mutant.fingerprint().matches(observation)) {
        return new FailureSource(history, observation);
      }
    }
    throw new IllegalStateException("M03 legacy semantic mutant survived: " + mutant.id());
  }

  private static List<RequiredMutant> requiredMutants() {
    return List.of(
        new RequiredMutant(
            M03Mutants.BEST_PRICE_LAST_ID,
            M03Mutants.bestPriceLast(M03ProductionCandidate::new),
            new M03Shrinker.Fingerprint("PRICE_TIME_PRIORITY", "WRONG_MAKER_ORDER")),
        new RequiredMutant(
            M03Mutants.SAME_PRICE_LIFO_ID,
            M03Mutants.samePriceLifo(M03ProductionCandidate::new),
            new M03Shrinker.Fingerprint("PRICE_TIME_PRIORITY", "WRONG_MAKER_ORDER")),
        new RequiredMutant(
            M03Mutants.TAKER_PRICE_ID,
            M03Mutants.takerPrice(M03ProductionCandidate::new),
            new M03Shrinker.Fingerprint("MAKER_PRICE", "TRADE_PRICE")),
        new RequiredMutant(
            M03Mutants.QUANTITY_OVERFLOW_ID,
            M03Mutants.tradeQuantityOverflow(M03ProductionCandidate::new),
            new M03Shrinker.Fingerprint("QUANTITY_PARTITION", "TRADE_EXCEEDS_REMAINDER")),
        new RequiredMutant(
            M03Mutants.CANCEL_GHOST_ID,
            M03Mutants.cancelGhostBook(M03ProductionCandidate::new),
            new M03Shrinker.Fingerprint("BOOK_LIFECYCLE_BIJECTION", "ACTIVE_ID_SET")),
        new RequiredMutant(
            M03Mutants.CANCELED_REUSE_ID,
            M03Mutants.canceledIdentityReuse(M03ProductionCandidate::new),
            new M03Shrinker.Fingerprint(
                "LIFECYCLE_IRREVERSIBILITY", "TERMINAL_OR_ACTIVE_ID_REUSED")));
  }

  private static int countLines(byte[] bytes) {
    int count = 0;
    for (byte value : bytes) {
      if (value == '\n') {
        count++;
      }
    }
    return count;
  }

  private static void require(boolean condition, String message) {
    if (!condition) {
      throw new IllegalStateException(message);
    }
  }

  private record RequiredMutant(
      String id, M03Candidate.Factory factory, M03Shrinker.Fingerprint fingerprint) {}

  private record FailureSource(
      M03GeneratedHistory history, M03PropertyJudge.Observation observation) {}

  record MutantFact(
      String id,
      String fingerprint,
      int historyIndex,
      String lane,
      String seed,
      int originalCommands,
      int minimizedCommands,
      int shrinkTrials,
      boolean oneMinimal) {}

  record Result(
      int histories,
      int commands,
      int bytes,
      int lines,
      String digest,
      int differentialComparisons,
      int ledgerChecks,
      int bookChecks,
      List<MutantFact> mutants,
      String systemErrorControl) {
    Result {
      mutants = List.copyOf(mutants);
    }
  }
}
